<?php
    $csvPath = '../csv/parcels.csv';
    $allParcels = [];
    if (($handle = fopen($csvPath, 'r')) !== FALSE) {
        while (($data = fgetcsv($handle, 0, ',', '"', '\\')) !== FALSE) {
            $allParcels[] = $data;
        }
        fclose($handle);
    }
    echo "<html>";
    echo "<head>";
    echo "<title>All Parcels</title>";
    echo "<style>";
    echo "body {";
    echo "display: flex;";
    echo "justify-content: center;";
    echo "align-items: center;";
    echo "min-height: 100vh;";
    echo "padding: 24px;";
    echo "position: relative;";
    echo "background: linear-gradient(";
    echo "237deg,";
    echo "rgba(184, 255, 220, 1) 0%,";
    echo "rgba(130, 139, 255, 1) 100%";
    echo ");";
    echo "}";
    echo "a {";
    echo "text-decoration: none;";
    echo "}";
    echo "p {";
    echo "font-family: 'Inter-Regular', Helvetica;";
    echo "font-weight: 400;";
    echo "color: #9999ad;";
    echo "font-size: 18px;";
    echo "}";
    echo "h1 {";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "font-family: 'Inter-Bold', Helvetica;";
    echo "font-weight: 700;";
    echo "color: #ffffff;";
    echo "font-size: 36px;";
    echo "text-align: center;";
    echo "margin: 0;";
    echo "}";
    echo ".card {";
    echo "display: flex;";
    echo "flex-direction: column;";
    echo "width: 100%;";
    echo "max-width: 700px;";
    echo "padding: 32px;";
    echo "gap: 24px;";
    echo "}";
    echo ".navigation {";
    echo "display: flex;";
    echo "margin-top: auto;";
    echo "flex-wrap: wrap;";
    echo "gap: 8px 16px;";
    echo "position: relative;";
    echo "align-self: stretch;";
    echo "width: 100%;";
    echo "justify-content: center;";
    echo "}";
    echo ".svg-icon {";
    echo "fill: #b8b8d6;";
    echo "transition: fill 0.3s ease;";
    echo "width: 24px;";
    echo "height: 100%;";
    echo "}";
    echo ".svg-icon:hover {";
    echo "fill: #727BFF;";
    echo "}";
    echo ".button-text {";
    echo "position: relative;";
    echo "width: fit-content;";
    echo "font-family: 'Inter-Bold', Helvetica;";
    echo "font-weight: 700;";
    echo "color: #ffffff;";
    echo "text-align: center;";
    echo "}";
    echo ".button-text-small {";
    echo "font-size: 14px;";
    echo "}";
    echo ".button-text-big {";
    echo "font-size: 18px;";
    echo "}";
    echo ".btn {";
    echo "border: none;";
    echo "display: inline-flex;";
    echo "align-items: center;";
    echo "justify-content: center;";
    echo "gap: 10px;";
    echo "padding: 12px 12px;";
    echo "position: relative;";
    echo "flex: 0 0 auto;";
    echo "border-radius: 8px;";
    echo "}";
    echo ".btn-primary {";
    echo "background-color: #727BFF;";
    echo "}";
    echo ".btn-home {";
    echo "background-color: #43bccf;";
    echo "}";
    echo ".btn-primary:hover,";
    echo ".btn-home:hover {";
    echo "background-color: #5064FF;";
    echo "transform: translateY(-1px);";
    echo "}";
    echo ".btn-home:hover {";
    echo "background-color: #2EB5CA;";
    echo "}";
    echo ".table-container {";
    echo "background-color: #ffffff;";
    echo "border-radius: 80px 12px;";
    echo "padding: clamp(16px, 5vw, 24px);";
    echo "max-height: 200px;";
    echo "overflow-y: auto;";
    echo "}";
    echo ".styled-table {";
    echo "width: 100%;";
    echo "font-family: 'Inter-Bold', Helvetica;";
    echo "font-weight: 500;";
    echo "margin-bottom: 0px;";
    echo "text-align: center;";
    echo "table-layout: fixed;";
    echo "}";
    echo ".styled-table th, .styled-table td {";
    echo "padding: 10px;";
    echo "}";
    echo ".styled-table th {";
    echo "color: #b8b8d6;";
    echo "font-weight: 200px;";
    echo "}";
    echo ".styled-table td {";
    echo "color: #727BFF;";
    echo "}";
    echo ".styled-table tbody tr:hover {";
    echo "background-color: #f3ffe5;";
    echo "}";
    echo ".visually-hidden {";
    echo "position: absolute;";
    echo "width: 1px;";
    echo "height: 1px;";
    echo "padding: 0;";
    echo "overflow: hidden;";
    echo "clip: rect(0, 0, 0, 0);";
    echo "white-space: nowrap;";
    echo "border-width: 0;";
    echo "}";
    echo "</style>";
    echo "</head>";
    echo "<body>";
    echo "<div class='card'>";
    echo "<h1>All Parcels</h1>";
    echo "<div class='table-container'>";
    echo "<table class='styled-table'>";
    echo "<thead>";
    echo "<tr>";
    echo "<th>Parcel ID</th>";
    echo "<th>Sender</th>";
    echo "<th>Weight</th>";
    echo "</tr>";
    echo "</thead>";
    echo "<tbody>";

    foreach ($allParcels as $parcel) {
        echo "<tr>";
        foreach ($parcel as $field) {
            echo "<td>" . htmlspecialchars($field) . "</td>";
        }
        echo "</tr>";
    }

    echo "</tbody>";
    echo "</table>";
    echo "</div>";
    echo "<div class='navigation'>";
    echo "<a href='/addParcel.html' class='btn btn-primary'>"; 
    echo "<span class='button-text button-text-big'>Add Another Parcel</span>";
    echo "</a>";

    echo "<a href='/' class='btn btn-home'>"; 
    echo "<span class='button-text button-text-big'>Back to Home</span>";
    echo "</a>";
    echo "</div>";
?>