#!/usr/bin/python3
import os
import urllib.parse

# 1. GET requests send data via Environment Variables
query_string = os.environ.get("QUERY_STRING", "")

# 2. Parse the string (keyword=42&sort=desc -> {'keyword': ['42'], 'sort': ['desc']})
params = urllib.parse.parse_qs(query_string)

# Extract values safely
keyword = params.get("keyword", ["None"])[0]
sort_order = params.get("sort", ["asc"])[0]

# 3. CGI scripts MUST print their own HTTP headers first
print("Content-Type: text/html")
print() # The empty line separates headers from the body

# 4. The HTML Body
print("<html>")
print("<head><title>Search Results</title></head>")
print("<body>")
print(f"<h1>Search Results for: {keyword}</h1>")
print(f"<p>Sorted by: <b>{sort_order}</b></p>")
print("<hr>")
print("<p><i>Generated by Python CGI</i></p>")
print("</body>")
print("</html>")